# Layers: common sets of useful operations
Most of the time when writing code for machine learning models you want to operate at a higher level of abstraction than individual operations and manipulation of individual variables.

Many machine learning models are expressible as the composition and stacking of relatively simple layers, and TensorFlow provides both a set of many common layers as a well as easy ways for you to write your own application-specific layers either from scratch or as the composition of existing layers.


In [3]:
import tensorflow as tf

tf.enable_eager_execution()

In [8]:
# In the tf.keras.layers package, layers are objects. To construct a layer,
# simply construct the object. Most layers take as a first argument the number
# of output dimensions / channels.
layer = tf.keras.layers.Dense(100)

# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to 
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

# To use a layer, simply call it.
layer(tf.zeros([10, 5]))

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [11]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using `layer.variables` and trainable variables using 
# `layer.trainable_variables`. In this case a fully-connected layer
# will have variables for weights and biases.
layer.variables

[<tf.Variable 'dense_7/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.59169453,  0.3449353 , -0.0204342 , -0.26731145, -0.49600327,
          0.52062684,  0.6180561 , -0.4679197 , -0.17638981,  0.20242763],
        [-0.5236215 ,  0.11118817,  0.573767  ,  0.23648125, -0.3478962 ,
          0.5672056 , -0.25587937, -0.5374807 ,  0.17584068, -0.14337152],
        [-0.15082067,  0.54284996, -0.19325423,  0.43534094,  0.28802055,
          0.05000985, -0.61812544, -0.13598529, -0.01569456, -0.27331197],
        [ 0.49850005, -0.03452665, -0.597116  ,  0.27175522, -0.33632916,
         -0.27198592, -0.02380764, -0.28046963, -0.42657903, -0.22869676],
        [ 0.1028946 , -0.54296595, -0.3883748 ,  0.11333013,  0.5429265 ,
         -0.30998358, -0.42744952,  0.5663753 , -0.3817624 , -0.24306247]],
       dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [12]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_7/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.59169453,  0.3449353 , -0.0204342 , -0.26731145, -0.49600327,
          0.52062684,  0.6180561 , -0.4679197 , -0.17638981,  0.20242763],
        [-0.5236215 ,  0.11118817,  0.573767  ,  0.23648125, -0.3478962 ,
          0.5672056 , -0.25587937, -0.5374807 ,  0.17584068, -0.14337152],
        [-0.15082067,  0.54284996, -0.19325423,  0.43534094,  0.28802055,
          0.05000985, -0.61812544, -0.13598529, -0.01569456, -0.27331197],
        [ 0.49850005, -0.03452665, -0.597116  ,  0.27175522, -0.33632916,
         -0.27198592, -0.02380764, -0.28046963, -0.42657903, -0.22869676],
        [ 0.1028946 , -0.54296595, -0.3883748 ,  0.11333013,  0.5429265 ,
         -0.30998358, -0.42744952,  0.5663753 , -0.3817624 , -0.24306247]],
       dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [14]:
# Implementing custom layers.
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs
    
  def build(self, input_shape):
    self.kernel = self.add_variable("kernel", 
                                    shape=[int(input_shape[-1]), 
                                           self.num_outputs])
    
  def call(self, input):
    return tf.matmul(input, self.kernel)
  
layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.41508526,  0.21526372, -0.21154436, -0.33377388,  0.00527161,
         0.16138947,  0.56288034,  0.48180968,  0.6081596 , -0.32375804],
       [ 0.2278207 , -0.49561936,  0.52052885,  0.18399972, -0.20992216,
        -0.6196499 ,  0.56582826,  0.572895  , -0.32005298,  0.15848768],
       [-0.5066173 , -0.6079595 ,  0.5603978 , -0.04223937, -0.5521766 ,
        -0.46521556, -0.06518131,  0.38910252,  0.5641542 , -0.48394585],
       [-0.54362154, -0.09792727,  0.1803925 , -0.39840907,  0.31647944,
        -0.5633205 , -0.4374131 , 

In [15]:
# Models: composing layers.
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)

    
block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization_v1/gamma:0', 'resnet_identity_block/batch_normalization_v1/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_v1_1/gamma:0', 'resnet_identity_block/batch_normalization_v1_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_v1_2/gamma:0', 'resnet_identity_block/batch_normalization_v1_2/beta:0']


In [19]:
# Much of the time, however, models which compose many layers simply call one layer after the other.
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(2, 1, 
                                                      padding='same'),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(3, (1, 1)),
                               tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=1251, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>